insert into bodies (name) values('Седан');
insert into bodies (name) values('Хэтчбэк 3 дв.');
insert into bodies (name) values('Хэтчбэк 5 дв.');
insert into bodies (name) values('Лифтбэк');
insert into bodies (name) values('Внедорожник');
insert into bodies (name) values('Универсал');
insert into bodies (name) values('Купе');
insert into bodies (name) values('Минивэн');
insert into bodies (name) values('Пикап');
insert into bodies (name) values('Лимузин');
insert into bodies (name) values('Фургон');
insert into bodies (name) values('Кабриолет');