insert into models (name, car_brand_id) values('A1', 1);
insert into models (name, car_brand_id) values('A2', 1);
insert into models (name, car_brand_id) values('A3', 1);
insert into models (name, car_brand_id) values('A4', 1);
insert into models (name, car_brand_id) values('A4 allroad', 1);
insert into models (name, car_brand_id) values('A5', 1);
insert into models (name, car_brand_id) values('A6', 1);
insert into models (name, car_brand_id) values('A6 allroad', 1);
insert into models (name, car_brand_id) values('A7', 1);
insert into models (name, car_brand_id) values('A8', 1);
insert into models (name, car_brand_id) values('S1', 1);
insert into models (name, car_brand_id) values('S2', 1);
insert into models (name, car_brand_id) values('S3', 1);
insert into models (name, car_brand_id) values('S4', 1);
insert into models (name, car_brand_id) values('S5', 1);
insert into models (name, car_brand_id) values('S6', 1);
insert into models (name, car_brand_id) values('S7', 1);
insert into models (name, car_brand_id) values('S8', 1);
insert into models (name, car_brand_id) values('RS 2', 1);
insert into models (name, car_brand_id) values('RS 3', 1);
insert into models (name, car_brand_id) values('RS 4', 1);
insert into models (name, car_brand_id) values('RS 5', 1);
insert into models (name, car_brand_id) values('RS 6', 1);
insert into models (name, car_brand_id) values('RS 7', 1);
insert into models (name, car_brand_id) values('TT', 1);
insert into models (name, car_brand_id) values('TTS', 1);
insert into models (name, car_brand_id) values('TT RS', 1);
insert into models (name, car_brand_id) values('Q2', 1);
insert into models (name, car_brand_id) values('Q3', 1);
insert into models (name, car_brand_id) values('Q4 e-tron', 1);
insert into models (name, car_brand_id) values('Q5', 1);
insert into models (name, car_brand_id) values('Q6', 1);
insert into models (name, car_brand_id) values('Q7', 1);
insert into models (name, car_brand_id) values('Q8', 1);
insert into models (name, car_brand_id) values('1 серии', 2);
insert into models (name, car_brand_id) values('2 серии', 2);
insert into models (name, car_brand_id) values('3 серии', 2);
insert into models (name, car_brand_id) values('4 серии', 2);
insert into models (name, car_brand_id) values('5 серии', 2);
insert into models (name, car_brand_id) values('6 серии', 2);
insert into models (name, car_brand_id) values('7 серии', 2);
insert into models (name, car_brand_id) values('8 серии', 2);
insert into models (name, car_brand_id) values('M1', 2);
insert into models (name, car_brand_id) values('M2', 2);
insert into models (name, car_brand_id) values('M3', 2);
insert into models (name, car_brand_id) values('M4', 2);
insert into models (name, car_brand_id) values('M5', 2);
insert into models (name, car_brand_id) values('M6', 2);
insert into models (name, car_brand_id) values('M8', 2);
insert into models (name, car_brand_id) values('X1', 2);
insert into models (name, car_brand_id) values('X2', 2);
insert into models (name, car_brand_id) values('X3', 2);
insert into models (name, car_brand_id) values('X4', 2);
insert into models (name, car_brand_id) values('X5', 2);
insert into models (name, car_brand_id) values('X6', 2);
insert into models (name, car_brand_id) values('X7', 2);
insert into models (name, car_brand_id) values('X3 M', 2);
insert into models (name, car_brand_id) values('X4 M', 2);
insert into models (name, car_brand_id) values('X5 M', 2);
insert into models (name, car_brand_id) values('X6 M', 2);
insert into models (name, car_brand_id) values('Z1', 2);
insert into models (name, car_brand_id) values('Z3', 2);
insert into models (name, car_brand_id) values('Z4', 2);
insert into models (name, car_brand_id) values('Z8', 2);
insert into models (name, car_brand_id) values('A-Класс', 3);
insert into models (name, car_brand_id) values('A-Класс AMG', 3);
insert into models (name, car_brand_id) values('B-Класс', 3);
insert into models (name, car_brand_id) values('C-Класс', 3);
insert into models (name, car_brand_id) values('C-Класс AMG', 3);
insert into models (name, car_brand_id) values('CL-Класс', 3);
insert into models (name, car_brand_id) values('CL-Класс AMG', 3);
insert into models (name, car_brand_id) values('CLA-Класс', 3);
insert into models (name, car_brand_id) values('CLA-Класс AMG', 3);
insert into models (name, car_brand_id) values('CLS-Класс', 3);
insert into models (name, car_brand_id) values('CLS-Класс AMG', 3);
insert into models (name, car_brand_id) values('E-Класс', 3);
insert into models (name, car_brand_id) values('E-Класс AMG', 3);
insert into models (name, car_brand_id) values('G-Класс', 3);
insert into models (name, car_brand_id) values('G-Класс AMG', 3);
insert into models (name, car_brand_id) values('G-Класс AMG 6x6', 3);
insert into models (name, car_brand_id) values('GL-Класс', 3);
insert into models (name, car_brand_id) values('GL-Класс AMG', 3);
insert into models (name, car_brand_id) values('GLA-Класс', 3);
insert into models (name, car_brand_id) values('GLA-Класс AMG', 3);
insert into models (name, car_brand_id) values('GLB-Класс', 3);
insert into models (name, car_brand_id) values('GLB-Класс AMG', 3);
insert into models (name, car_brand_id) values('GLC-Класс', 3);
insert into models (name, car_brand_id) values('GLC-Класс AMG', 3);
insert into models (name, car_brand_id) values('GLE-Класс', 3);
insert into models (name, car_brand_id) values('GLE-Класс AMG', 3);
insert into models (name, car_brand_id) values('GLK-Класс', 3);
insert into models (name, car_brand_id) values('GLS-Класс', 3);
insert into models (name, car_brand_id) values('GLS-Класс AMG', 3);
insert into models (name, car_brand_id) values('M-Класс', 3);
insert into models (name, car_brand_id) values('M-Класс AMG', 3);
insert into models (name, car_brand_id) values('R-Класс', 3);
insert into models (name, car_brand_id) values('R-Класс AMG', 3);
insert into models (name, car_brand_id) values('S-Класс', 3);
insert into models (name, car_brand_id) values('S-Класс AMG', 3);
insert into models (name, car_brand_id) values('V-Класс', 3);
insert into models (name, car_brand_id) values('Viano', 3);
insert into models (name, car_brand_id) values('Vito', 3);
insert into models (name, car_brand_id) values('3', 4);
insert into models (name, car_brand_id) values('6', 4);
insert into models (name, car_brand_id) values('CX-3', 4);
insert into models (name, car_brand_id) values('CX-30', 4);
insert into models (name, car_brand_id) values('CX-4', 4);
insert into models (name, car_brand_id) values('CX-5', 4);
insert into models (name, car_brand_id) values('CX-50', 4);
insert into models (name, car_brand_id) values('CX-60', 4);
insert into models (name, car_brand_id) values('CX-7', 4);
insert into models (name, car_brand_id) values('CX-9', 4);
insert into models (name, car_brand_id) values('Accent', 5);
insert into models (name, car_brand_id) values('Creta', 5);
insert into models (name, car_brand_id) values('Elantra', 5);
insert into models (name, car_brand_id) values('Getz', 5);
insert into models (name, car_brand_id) values('Grand Starex', 5);
insert into models (name, car_brand_id) values('ix35', 5);
insert into models (name, car_brand_id) values('Palisade', 5);
insert into models (name, car_brand_id) values('Santa Fe', 5);
insert into models (name, car_brand_id) values('Solaris', 5);
insert into models (name, car_brand_id) values('Staria', 5);
insert into models (name, car_brand_id) values('Tuscon', 5);
insert into models (name, car_brand_id) values('Carnival', 6);
insert into models (name, car_brand_id) values('Ceed', 6);
insert into models (name, car_brand_id) values('Cerato', 6);
insert into models (name, car_brand_id) values('K5', 6);
insert into models (name, car_brand_id) values('K7', 6);
insert into models (name, car_brand_id) values('Mohave', 6);
insert into models (name, car_brand_id) values('Optima', 6);
insert into models (name, car_brand_id) values('Rio', 6);
insert into models (name, car_brand_id) values('Seltos', 6);
insert into models (name, car_brand_id) values('Sorento', 6);
insert into models (name, car_brand_id) values('Soul', 6);
insert into models (name, car_brand_id) values('Spectra', 6);
insert into models (name, car_brand_id) values('Sportage', 6);
insert into models (name, car_brand_id) values('Defender', 7);
insert into models (name, car_brand_id) values('Discovery', 7);
insert into models (name, car_brand_id) values('Discovery Sport', 7);
insert into models (name, car_brand_id) values('Range Rover', 7);
insert into models (name, car_brand_id) values('Range Rover Evoque', 7);
insert into models (name, car_brand_id) values('Range Rover Sport', 7);
insert into models (name, car_brand_id) values('Range Rover Velar', 7);
insert into models (name, car_brand_id) values('E-Pace', 8);
insert into models (name, car_brand_id) values('F-Pace', 8);
insert into models (name, car_brand_id) values('I-Pace', 8);
insert into models (name, car_brand_id) values('E-Type', 8);
insert into models (name, car_brand_id) values('F-Type', 8);
insert into models (name, car_brand_id) values('XE', 8);
insert into models (name, car_brand_id) values('XF', 8);
insert into models (name, car_brand_id) values('XJ', 8);
insert into models (name, car_brand_id) values('Cabrio', 9);
insert into models (name, car_brand_id) values('Clubman', 9);
insert into models (name, car_brand_id) values('Countryman', 9);
insert into models (name, car_brand_id) values('Coupe', 9);
insert into models (name, car_brand_id) values('Hatch', 9);
insert into models (name, car_brand_id) values('Paceman', 9);
insert into models (name, car_brand_id) values('Roadster', 9);
insert into models (name, car_brand_id) values('G70', 10);
insert into models (name, car_brand_id) values('G80', 10);
insert into models (name, car_brand_id) values('G90', 10);
insert into models (name, car_brand_id) values('GV60', 10);
insert into models (name, car_brand_id) values('GV70', 10);
insert into models (name, car_brand_id) values('GV80', 10);